export let globalConfig = {
	lang: 'en',
	name: '',
	soundVolume: 100,
	musicVolume: 100,
	wikiLinkMode: 1,
	saveReminder: 60,
	badgeHints: true,
	playBadgeHintSound: true,
	chatTipIndex: -1,
	gameChat: true,
	gameChatGlobal: false,
	gameChatParty: true,
	tabToChat: true,
	mapChatHistoryLimit: 100,
	globalChatHistoryLimit: 100,
	partyChatHistoryLimit: 250,
	mobileControls: true,
	mobileControlsType: 'default',
	playMentionSound: true,
	blurScreenshotEmbeds: false,
	locationDisplay: false,
	hideRankings: false,
	hideSchedules: false,
	autoDownloadScreenshots: false,
	screenshotResolution: 1,
	preloads: false,
	questionablePreloads: false,
	rulesReviewed: false,
	warningsReviewed: false,
	badgeToolsData: null,
	pushNotificationToastDismissed: false,
	unicodeFont: false
};

export let config = {
	privateMode: false,
	singleplayerMode: false,
	disableChat: false,
	mute: false,
	hideLocation: false,
	nametagMode: 1,
	disablePlayerSounds: false,
	immersionMode: false,
	chatTabIndex: 0,
	playersTabIndex: 0,
	globalMessage: false,
	hideGlobalMessageLocations: false,
	filterMentions: false,
	trackedLocationId: null,
	hideUnnamedPlayers: false,

	fontStyle: 0,
	uiTheme: 'Default'
};
