// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import { initFormatters } from './formatters';
import type { Locales, Translations } from './i18n-types';
import { loadedFormatters, loadedLocales, locales } from './i18n-util';

import ar from './ar';
import de from './de';
import en from './en';
import eo from './eo';
import es from './es';
import fr from './fr';
import id from './id';
import it from './it';
import ja from './ja';
import ko from './ko';
import pl from './pl';
import pt from './pt';
import ro from './ro';
import ru from './ru';
import tr from './tr';
import uk from './uk';
import vi from './vi';
import zh from './zh';

const localeTranslations = {
  ar,
  de,
  en,
  eo,
  es,
  fr,
  id,
  it,
  ja,
  ko,
  pl,
  pt,
  ro,
  ru,
  tr,
  uk,
  vi,
  zh
};

export const loadLocale = (locale: Locales): void => {
  if (loadedLocales[locale]) return;

  loadedLocales[locale] = localeTranslations[locale] as unknown as Translations;
  loadFormatters(locale);
};

export const loadAllLocales = (): void => locales.forEach(loadLocale);

export const loadFormatters = (locale: Locales): void => void (loadedFormatters[locale] = initFormatters(locale));
